### ISSUE TITLE
TypeError: Cannot read property 'decorators' of undefined

### ISSUE THREAD

**Issue by jeffreywescott** [stemey/baucis-gform#1]
Using the latest release candidates of [baucis](https://github.com/wprl/baucis), calling `require("baucis-gform") gives an error:

```
  TypeError: Cannot read property 'decorators' of undefined
    at Object.<anonymous> (/Users/jeffrey/dev/wisdomlabs/wisdomlabs/node_modules/baucis-gform/index.js:8:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (/Users/jeffrey/dev/wisdomlabs/wisdomlabs/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.module.exports.initialize (/Users/jeffrey/dev/wisdomlabs/wisdomlabs/api/index.coffee:68:5)
    at Object.<anonymous> (/Users/jeffrey/dev/wisdomlabs/wisdomlabs/server.coffee:55:5)
    at Object.<anonymous> (/Users/jeffrey/dev/wisdomlabs/wisdomlabs/server.coffee:1:1)
    at Module._compile (module.js:460:26)
```

There doesn't seem to be a `Release` property on the baucis object anymore.

``` javascript
baucis.Release.decorators(decorators.Release);
```

**Comment by stemey** [comment]
Fixed with update to baucis 1.0.5. Initialization has changed a bit.
